apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-modifier-deployment
  namespace: image-modifier
spec:
  selector:
    matchLabels:
      app: image-modifier
  template:
    metadata:
      labels:
        app: image-modifier
    spec:
      containers:
      - name: image-modifier
        image: IMAGE_NAME
        resources:
          limits:
            memory: "800Mi"  # Increase from 128Mi to 256Mi (or higher)
            cpu: "2000m"
          requests:
            memory: "500Mi"  # Set request to the minimum required memory
            cpu: "1000m"      # Ensure CPU request is reasonable
        ports:
        - containerPort: 5000
