apiVersion: v1
kind: Service
metadata:
  name: image-modifier-service
  namespace: lab-demo
spec:
  selector:
    app: image-modifier
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 32005
  type: NodePort
