apiVersion: v1
kind: Service
metadata:
  name: image-modifier-service
  namespace: image-modifier
spec:
  selector:
    app: image-modifier
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32005
  type: NodePort
